use std::process::{Command, Stdio};
use std::error::Error;
use std::io::{BufRead, BufReader, Write};
use std::thread;
use std::time::{Duration, Instant};
use std::path::PathBuf;
use std::fs::{self};
use serde::Serialize;
use crate::device_discovery::Device;
use crate::plan::WipePlan;
use chrono::Utc;
use sha2::{Sha256, Digest};
use base64;
use base64::Engine;
use serde_json::json;
use std::env;

#[derive(Serialize, Debug)]
pub struct WipeCertificate {
    pub device: String,
    pub method: String,
    pub device_label: Option<String>,
    pub timestamp: String,
    pub success: bool,
    pub simulated: bool,
    pub operator: Option<String>,
    pub duration_seconds: u64,
    pub cert_id: String,
    pub payload_hash: String,
    pub signature_b64: Option<String>,
}

fn certificate_dir() -> PathBuf {
    let mut p = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
    p.push("certificates");
    p
}

fn ensure_cert_subdirs() -> Result<(), Box<dyn Error>> {
    let dir = certificate_dir();
    fs::create_dir_all(dir.join("keys"))?;
    fs::create_dir_all(dir.join("payloads"))?;
    fs::create_dir_all(dir.join("signatures"))?;
    fs::create_dir_all(dir.join("archives"))?;
    Ok(())
}

fn save_certificate_json(cert: &WipeCertificate) -> Result<PathBuf, Box<dyn Error>> {
    ensure_cert_subdirs()?;
    let dir = certificate_dir();
    let filename = format!("wipe_certificate_{}_{}.json", cert.device, cert.timestamp.replace(':', "-").replace('+', "-").replace('Z', "Z"));
    let mut path = dir.join("archives");
    path.push(filename);
    let json = serde_json::to_string_pretty(cert)?;
    fs::write(&path, json)?;
    Ok(path)
}

fn render_certificate_html(cert: &WipeCertificate) -> String {
        let success_str = if cert.success { "SUCCESS" } else { "FAILURE" };
        let label_line = match &cert.device_label {
                Some(l) => format!("<tr><th>Device Label</th><td>{}</td></tr>", html_escape::encode_text(l)),
                None => String::new(),
        };
    let operator_line = match &cert.operator {
        Some(o) => format!("<tr><th>Operator</th><td>{}</td></tr>", html_escape::encode_text(o)),
        None => String::new(),
    };
    // When `simulated` is true the run was non-destructive (simulation),
    // so display "No (simulated)" for destructive.
    let simulated_line = format!("<tr><th>Destructive</th><td>{}</td></tr>", if cert.simulated { "No (simulated)" } else { "Yes (real)" });
    let duration_line = format!("<tr><th>Duration (s)</th><td>{}</td></tr>", cert.duration_seconds);
    let certid_line = format!("<tr><th>Certificate ID</th><td>{}</td></tr>", html_escape::encode_text(&cert.cert_id));
    let hash_line = format!("<tr><th>Payload SHA256</th><td>{}</td></tr>", html_escape::encode_text(&cert.payload_hash));
    let signature_line = match &cert.signature_b64 {
        Some(s) => format!("<tr><th>Signature (base64)</th><td style=\"word-break:break-all;max-width:600px;\">{}</td></tr>", html_escape::encode_text(s)),
        None => String::new(),
    };

        format!(r#"
<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Wipe Certificate - {device}</title>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 40px; color: #222; }}
            header {{ text-align: center; margin-bottom: 24px; }}
            h1 {{ margin: 0; font-size: 24px; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 12px; }}
            th {{ text-align: left; width: 200px; padding: 8px; background: #f6f6f6; }}
            td {{ padding: 8px; }}
            .status {{ font-weight: bold; color: {status_color}; }}
            footer {{ margin-top: 40px; font-size: 12px; color: #666; text-align: center; }}
        </style>
    </head>
    <body>
        <header>
            <h1>Wipe Certificate</h1>
            <div>Generated by obliterator-discovery</div>
        </header>
        <table>
            <tr><th>Device</th><td>{device}</td></tr>
            {label_line}
            <tr><th>Method</th><td>{method}</td></tr>
            <tr><th>Timestamp (UTC)</th><td>{timestamp}</td></tr>
            {operator_line}
            {simulated_line}
            {duration_line}
            {certid_line}
            {hash_line}
            {signature_line}
            <tr><th>Result</th><td class="status">{result}</td></tr>
        </table>
        <footer>
            This certificate attests the wipe action performed by the system. Treat as formal record.
        </footer>
    </body>
</html>
"#,
                device = html_escape::encode_text(&cert.device),
                label_line = label_line,
                method = html_escape::encode_text(&cert.method),
                timestamp = html_escape::encode_text(&cert.timestamp),
                result = success_str,
                status_color = if cert.success { "green" } else { "red" }
        )
}

fn save_certificate_html_and_pdf(cert: &WipeCertificate) -> Result<(PathBuf, Option<PathBuf>), Box<dyn Error>> {
    ensure_cert_subdirs()?;
    let dir = certificate_dir();
    let base = format!("wipe_certificate_{}_{}", cert.device, cert.timestamp.replace(':', "-").replace('+', "-").replace('Z', "Z"));
    let mut html_path = dir.join("archives");
    html_path.push(format!("{}.html", base));
    let html = render_certificate_html(cert);
    fs::write(&html_path, html)?;

    // Try to generate PDF with wkhtmltopdf if available
    let mut pdf_path = dir.join("archives");
    pdf_path.push(format!("{}.pdf", base));

    let wk = Command::new("wkhtmltopdf").arg("--version").output();
    if wk.is_ok() {
            let output = Command::new("wkhtmltopdf")
                    .arg(html_path.to_str().unwrap())
                    .arg(pdf_path.to_str().unwrap())
                    .output();
            match output {
                    Ok(out) if out.status.success() => return Ok((html_path, Some(pdf_path))),
                    Ok(out) => {
                            eprintln!("wkhtmltopdf failed: {}", String::from_utf8_lossy(&out.stderr));
                            return Ok((html_path, None));
                    }
                    Err(e) => {
                            eprintln!("failed to execute wkhtmltopdf: {}", e);
                            return Ok((html_path, None));
                    }
            }
    }

    // If wkhtmltopdf not available, return HTML only
    Ok((html_path, None))
}

/// Show a spinner for operations where progress is unknown (NVMe/SATA secure erase)
fn spinner_simulate(message: &str, seconds: u64) {
    let spinner_chars = ['|', '/', '-', '\\'];
    for i in 0..seconds * 10 {
        let c = spinner_chars[i as usize % spinner_chars.len()];
        print!("\r{} {}", message, c);
        std::io::stdout().flush().unwrap();
        thread::sleep(Duration::from_millis(100));
    }
    println!("\r{} done.", message);
}

/// Overwrite a device with zeroes, showing live progress
fn overwrite_with_progress(dev_path: &str, simulate: bool) -> bool {
    if simulate {
        println!("Simulating overwrite for {}", dev_path);
        return true;
    }

    println!("Starting overwrite for {}", dev_path);

    let mut cmd = Command::new("sudo")
        .args(&["dd", "if=/dev/zero", &format!("of={}", dev_path), "bs=4M", "status=progress"])
        .stdout(Stdio::piped())
        .spawn()
        .expect("failed to spawn dd");

    let stdout = cmd.stdout.take().unwrap();
    let reader = BufReader::new(stdout);

    for line in reader.lines() {
        if let Ok(l) = line {
            // dd progress lines start with bytes copied
            if let Some(bytes_str) = l.split_whitespace().next() {
                if let Ok(bytes_written) = bytes_str.parse::<u64>() {
                    print!("\rBytes written: {}", bytes_written);
                    std::io::stdout().flush().unwrap();
                }
            }
        }
    }

    match cmd.wait() {
        Ok(status) => status.success(),
        Err(e) => {
            eprintln!("Error during overwrite: {}", e);
            false
        }
    }
}

/// Execute the wipe according to the plan
pub fn execute_wipe(device: &Device, plan: &WipePlan, simulate: bool) -> WipeCertificate {
    println!(
        "{} wipe requested for device {} (simulate: {})",
        match plan.method {
            crate::plan::WipeMethod::NvmeFormat => "NVMe Format",
            crate::plan::WipeMethod::AtaSecureErase => "ATA Secure Erase",
            crate::plan::WipeMethod::Overwrite => "Overwrite",
        },
        device.name,
        simulate
    );

    let start_instant = Instant::now();
    let start_ts = Utc::now();

    let success = match plan.method {
        crate::plan::WipeMethod::Overwrite => {
            let dev_path = &format!("/dev/{}", device.name);
            overwrite_with_progress(dev_path, simulate)
        }
        crate::plan::WipeMethod::NvmeFormat => {
            if simulate {
                spinner_simulate(&format!("Simulating NVMe format on {}", device.name), 10);
                true
            } else {
                let dev_path = &format!("/dev/{}", device.name);
                let output = Command::new("sudo")
                    .args(&["nvme", "format", dev_path])
                    .output();
                match output {
                    Ok(out) if out.status.success() => true,
                    Ok(out) => {
                        eprintln!("nvme format failed: {}", String::from_utf8_lossy(&out.stderr));
                        false
                    }
                    Err(e) => {
                        eprintln!("failed to execute nvme format: {}", e);
                        false
                    }
                }
            }
        }
        crate::plan::WipeMethod::AtaSecureErase => {
            if simulate {
                spinner_simulate(&format!("Simulating SATA secure erase on {}", device.name), 10);
                true
            } else {
                let dev_path = &format!("/dev/{}", device.name);
                let output = Command::new("sudo")
                    .args(&["hdparm", "--security-erase", "NULL", dev_path])
                    .output();
                match output {
                    Ok(out) if out.status.success() => true,
                    Ok(out) => {
                        eprintln!("hdparm erase failed: {}", String::from_utf8_lossy(&out.stderr));
                        false
                    }
                    Err(e) => {
                        eprintln!("failed to execute hdparm: {}", e);
                        false
                    }
                }
            }
        }
    };

    // compute duration and operator
    let duration_seconds = start_instant.elapsed().as_secs();
    let operator = env::var("USER").ok();

    // Build canonical payload (excluding signature) for hashing/signing
    let payload = json!({
        "tool": "obliterator-discovery",
        "version": "0.1.0",
        "device": device.name,
        "device_label": device.label,
        "method": format!("{:?}", plan.method),
        "timestamp": start_ts.to_rfc3339(),
        "simulated": simulate,
        "operator": operator.clone(),
        "duration_seconds": duration_seconds,
        "success": success
    });

    let payload_bytes = match serde_json::to_vec(&payload) {
        Ok(b) => b,
        Err(e) => {
            eprintln!("Failed to serialize payload for signing: {}", e);
            Vec::new()
        }
    };

    // compute SHA256 of payload
    let mut hasher = Sha256::new();
    hasher.update(&payload_bytes);
    let payload_hash = format!("{:x}", hasher.finalize());

    // prepare certificate id (shortened hash)
    let cert_id = if payload_hash.len() > 16 { payload_hash[0..16].to_string() } else { payload_hash.clone() };

    // Attempt to sign the payload using openssl; if unavailable, leave signature None
    let mut signature_b64: Option<String> = None;
    let cert_dir = certificate_dir();
    let keys_dir = cert_dir.join("keys");
    if Command::new("openssl").arg("version").output().is_ok() {
        let _ = ensure_cert_subdirs();
        let priv_key = keys_dir.join("private.pem");
        let pub_key = keys_dir.join("public.pem");

        if !priv_key.exists() {
            // generate a 2048-bit RSA key
            match Command::new("openssl").args(&["genpkey", "-algorithm", "RSA", "-out", priv_key.to_str().unwrap(), "-pkeyopt", "rsa_keygen_bits:2048"]).output() {
                Ok(_) => {
                    // export public key
                    let _ = Command::new("openssl").args(&["rsa", "-pubout", "-in", priv_key.to_str().unwrap(), "-out", pub_key.to_str().unwrap()]).output();
                    println!("Generated cryptographic key pair for certificate signing");
                }
                Err(e) => eprintln!("Failed to generate private key: {}", e),
            }
        }

        if priv_key.exists() {
            // write payload to temporary file in payloads directory
            let payload_path = cert_dir.join("payloads").join(format!("payload_{}.json", cert_id));
            if let Err(e) = fs::write(&payload_path, &payload_bytes) {
                eprintln!("Failed to write payload file for signing: {}", e);
            } else {
                let sig_bin = cert_dir.join("signatures").join(format!("payload_{}.sig", cert_id));
                let sign_out = Command::new("openssl").args(&["dgst", "-sha256", "-sign", priv_key.to_str().unwrap(), "-out", sig_bin.to_str().unwrap(), payload_path.to_str().unwrap()]).output();
                match sign_out {
                    Ok(out) if out.status.success() => {
                        match fs::read(&sig_bin) {
                            Ok(sig_bytes) => {
                                signature_b64 = Some(base64::engine::general_purpose::STANDARD.encode(&sig_bytes));
                                println!("Signature saved: {}", sig_bin.display());
                            }
                            Err(e) => eprintln!("Failed to read signature file: {}", e),
                        }
                    }
                    Ok(out) => eprintln!("openssl signing failed: {}", String::from_utf8_lossy(&out.stderr)),
                    Err(e) => eprintln!("failed to execute openssl for signing: {}", e),
                }
                // payload & signature files are left for audit trail
            }
        }
    } else {
        eprintln!("openssl not available: signature will be omitted");
    }

    let cert = WipeCertificate {
        device: device.name.clone(),
        method: format!("{:?}", plan.method),
        device_label: device.label.clone(),
        timestamp: start_ts.to_rfc3339(),
        success,
        simulated: simulate,
        operator: operator.clone(),
        duration_seconds,
        cert_id: cert_id.clone(),
        payload_hash: payload_hash.clone(),
        signature_b64: signature_b64.clone(),
    };

    // Save certificate JSON and HTML/PDF (if possible). Print locations to user.
    match save_certificate_json(&cert) {
        Ok(p) => println!("Wipe certificate saved: {}", p.display()),
        Err(e) => eprintln!("Failed to save certificate JSON: {}", e),
    }

    match save_certificate_html_and_pdf(&cert) {
        Ok((html, Some(pdf))) => println!("Certificate HTML: {}, PDF: {}", html.display(), pdf.display()),
        Ok((html, None)) => println!("Certificate HTML written: {} (PDF generation unavailable)", html.display()),
        Err(e) => eprintln!("Failed to write certificate HTML/PDF: {}", e),
    }

    cert
}